os: linux
sudo: false
language: python

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
    - python: 3.6
      env: TOXENV=py36
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=coverage
  fast_finish: true

install:
  - pip install tox

script:
  - tox

cache:
  - pip

branches:
  only:
    - master
    - /^.*-maintenance$/

notifications:
  email: false
